name: Wise cow says wise stuff
on: push
jobs:
  Cowsay:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
          cache: 'pip'
      - run: pip install python-cowsay
      - run: git update-index --chmod=+x ci/cowsay.py
      - run: ci/cowsay.py
          
    
