name: Reusable-workflow
on: 
  workflow_call:
    inputs:
      who-to-greet:
        description: 'A username passed from the caller workflow'
        default: there!
        required: true
        type: string
    outputs:
      current_time:
        description: 'Current time'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps: 
      - name: Hello console
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: set time
        id: time
        run: time=$(date) >> $GITHUB_OUTPUT
  
