name: Reusable-workflow
on: 
  workflow_call:
    inputs:
      who_to_greet:
        description: 'A username passed from the caller workflow'
        default: 'there!'
        required: true
        type: string
    outputs:
      current_time:
        description: 'Current time'
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello console
        run: echo "Hello ${{ who_to_greet }}"
      - name: set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
  
